import '../models/models.dart';

class TeamsRepository {
  static final List<LeagueModel> soccerLeagues = [
    LeagueModel(
      id: 0,
      name: "Premier League",
      asset: 'assets/png/epl.png',
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.soccer,
          name: "Manchester United",
          logo: 'assets/png/man_united.png',
          rating: 5,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.soccer,
          name: "Manchester City",
          logo: 'assets/png/man_city.png',
          rating: 5,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.soccer,
          name: "Chelsea",
          logo: 'assets/png/chelsea.png',
          rating: 5,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.soccer,
          name: "Tottenham Hotspur",
          logo: 'assets/png/spurs.png',
          rating: 4,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.soccer,
          name: "Aston Villa",
          logo: 'assets/png/aston_villa.png',
          rating: 4,
        ),
        TeamModel(
          id: 5,
          sportType: SportType.soccer,
          name: "Bournemouth",
          logo: 'assets/png/bournemouth.png',
          rating: 3,
        ),
        TeamModel(
          id: 6,
          sportType: SportType.soccer,
          name: "Everton",
          logo: 'assets/png/everton.png',
          rating: 4,
        ),
      ],
    ),
    LeagueModel(
      id: 1,
      name: "LaLiga",
      asset: 'assets/png/laliga.png',
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.soccer,
          name: "Real Madrid",
          logo: 'assets/png/real_madrid.png',
          rating: 5,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.soccer,
          name: "Barcelona",
          logo: 'assets/png/barca.png',
          rating: 5,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.soccer,
          name: "Atletico",
          logo: 'assets/png/atm_madrid.png',
          rating: 5,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.soccer,
          name: "Real Sociedad",
          logo: 'assets/png/real_sos.png',
          rating: 3,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.soccer,
          name: "Celta Vigo",
          logo: 'assets/png/celta_vigo.png',
          rating: 3,
        ),
      ],
    ),
    LeagueModel(
      id: 2,
      name: "Bundesliga",
      asset: 'assets/png/bundesliga.png',
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.soccer,
          name: "Bayern Munich",
          logo: 'assets/png/bayern.png',
          rating: 5,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.soccer,
          name: "Bayer Leverkusen",
          logo: 'assets/png/bvb04.png',
          rating: 5,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.soccer,
          name: "Borussia Dortmund",
          logo: 'assets/png/bvb.png',
          rating: 5,
        ),
        TeamModel(
          sportType: SportType.soccer,
          id: 3,
          name: "Wolfsburg",
          logo: 'assets/png/wolf.png',
          rating: 3,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.soccer,
          name: "Cologne",
          logo: 'assets/png/koln.png',
          rating: 4,
        ),
      ],
    ),
  ];

  static final List<LeagueModel> footballLeagues = [
    LeagueModel(
      id: 0,
      name: "NFL",
      asset: "assets/png/nfl.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.football,
          name: "New York Jets",
          logo: 'assets/png/jets.png',
          rating: 3,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.football,
          name: "Pittsburgh Steelers",
          logo: 'assets/png/steelers.png',
          rating: 5,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.football,
          name: "Indianapolis Colts",
          logo: 'assets/png/colts.png',
          rating: 4,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.football,
          name: "Cleveland Browns",
          logo: 'assets/png/browns.png',
          rating: 2,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.football,
          name: "New England Patriots",
          logo: 'assets/png/patriots.png',
          rating: 5,
        ),
      ],
    ),
    LeagueModel(
      id: 1,
      name: "NCAA",
      asset: "assets/png/ncaa.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.football,
          name: "Alabama",
          logo: 'assets/png/alabama.png',
          rating: 5,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.football,
          name: "Arkansas",
          logo: 'assets/png/arkansas.png',
          rating: 3,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.football,
          name: "Auburn",
          logo: 'assets/png/auburn.png',
          rating: 4,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.football,
          name: "Florida Gators",
          logo: 'assets/png/gators.png',
          rating: 2,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.football,
          name: "Georgia",
          logo: 'assets/png/georgia.png',
          rating: 4,
        ),
      ],
    ),
    LeagueModel(
      id: 2,
      name: "F1",
      asset: "assets/png/f1.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.football,
          name: "Albany Firebirds",
          logo: 'assets/png/firebirds.png',
          rating: 3,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.football,
          name: "Nashville Kats",
          logo: 'assets/png/kats.png',
          rating: 2,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.football,
          name: "Billings Outlaws",
          logo: 'assets/png/outlaws.png',
          rating: 5,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.football,
          name: "Oregon Lightning",
          logo: 'assets/png/lightning.png',
          rating: 4,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.football,
          name: "Washington Wolfpack",
          logo: 'assets/png/wolfpack.png',
          rating: 5,
        ),
      ],
    ),
  ];

  static final List<LeagueModel> basketballLeagues = [
    LeagueModel(
      id: 0,
      name: "Endesa",
      asset: "assets/png/endesa.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.basketball,
          name: "Valencia",
          logo: 'assets/png/valencia.png',
          rating: 4,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.basketball,
          name: "Tenerife",
          logo: 'assets/png/tenerife.png',
          rating: 3,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.basketball,
          name: "Unicaja",
          logo: 'assets/png/unicaja.png',
          rating: 5,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.basketball,
          name: "Joventut Badalona",
          logo: 'assets/png/badalona.png',
          rating: 2,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.basketball,
          name: "Gran Canaria",
          logo: 'assets/png/canaria.png',
          rating: 3,
        ),
      ],
    ),
    LeagueModel(
      id: 1,
      name: "LBA",
      asset: "assets/png/lba.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.basketball,
          name: "Milan",
          logo: 'assets/png/milan.png',
          rating: 5,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.basketball,
          name: "Varese",
          logo: 'assets/png/varese.png',
          rating: 3,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.basketball,
          name: "Basket Napoli",
          logo: 'assets/png/napoli.png',
          rating: 4,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.basketball,
          name: "Treviso",
          logo: 'assets/png/treviso.png',
          rating: 2,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.basketball,
          name: "Cantù",
          logo: 'assets/png/cantu.png',
          rating: 3,
        ),
      ],
    ),
    LeagueModel(
      id: 2,
      name: "NBA",
      asset: "assets/png/nba.png",
      teams: [
        TeamModel(
          id: 0,
          sportType: SportType.basketball,
          name: "Dallas",
          logo: 'assets/png/dallas.png',
          rating: 4,
        ),
        TeamModel(
          id: 1,
          sportType: SportType.basketball,
          name: "Denver",
          logo: 'assets/png/denver.png',
          rating: 3,
        ),
        TeamModel(
          id: 2,
          sportType: SportType.basketball,
          name: "Houston",
          logo: 'assets/png/houston.png',
          rating: 5,
        ),
        TeamModel(
          id: 3,
          sportType: SportType.basketball,
          name: "Clippers",
          logo: 'assets/png/clippers.png',
          rating: 2,
        ),
        TeamModel(
          id: 4,
          sportType: SportType.basketball,
          name: "Lakers",
          logo: 'assets/png/lakers.png',
          rating: 5,
        ),
      ],
    ),
  ];
}
